local ZombiesData = {
    
    ["ClassicZombie"] = {
       ["HP"] = 30,
       ["MaxHP"] = 30,
       ["Defense"] = 0,
       ["ModelName"] = "ClassicZombie", 
       ["ModelTypeTag"] = "Zombie",
       ["AttackClosePlant"] = "Bite",
       ["Class"] = "ClassicZombie",
       ["Name"] = "ClassicZombie",
       ["Team"] = "Zombies",
    },

    ["ConeHeadZombie"] = {
        ["HP"] = 40, 
        ["MaxHP"] = 40,
        ["Defense"] = 5,
        ["ModelName"] = "ConeHeadZombie",
        ["ModelTypeTag"] = "Zombie",
        ["AttackClosePlant"] = "Bite",
        ["Class"] = "ClassicZombie",
        ["Name"] = "ClassicZombie",
        ["Team"] = "Zombies",
    },

    ["BucketHeadZombie"] = {
        ["HP"] = 50,
        ["Defense"] = 10,
        ["MaxHP"] = 50,
        ["ModelName"] = "BucketHeadZombie",
        ["ModelTypeTag"] = "Zombie",
        ["AttackClosePlant"] = "Bite",
        ["Class"] = "ClassicZombie",
        ["Name"] = "ClassicZombie",
        ["Team"] = "Zombies",
    },


}
return ZombiesData 