local ZombiesData = {
    
    ["ClassicZombie"] = {
       ["HP"] = 30,
       ["MaxHP"] = 30,
       ["ModelName"] = "ClassicZombie", 
       ["ModelTypeTag"] = "Zombie",
       ["Class"] = "ClassicZombie",
    },

    ["ConeHeadZombie"] = {
        ["HP"] = 40, 
        ["MaxHP"] = 40,
        ["ModelName"] = "ConeHeadZombie",
        ["ModelTypeTag"] = "Zombie",
        ["Class"] = "ClassicZombie",
    },

    ["BucketHeadZombie"] = {
        ["HP"] = 50,
        ["MaxHP"] = 50,
        ["ModelName"] = "BucketHeadZombie",
        ["ModelTypeTag"] = "Zombie",
        ["Class"] = "ClassicZombie",
    },


}
return ZombiesData 