local ZombiesData = {
    
    ["ClassicZombie"] = {
       ["HP"] = 30,
       ["MaxHP"] = 30,
       ["BiteDamage"] = 10, 
       ["BiteCooldown"] = 5,    
       ["ModelName"] = "ClassicZombie", 
       ["ModelTypeTag"] = "Zombie",
       ["Class"] = "CommonZombie",
    },

    ["ConeHeadZombie"] = {
        ["BiteDamage"] = 15,
        ["HP"] = 40, 
        ["MaxHP"] = 40,
        ["BiteCooldown"] = 5,
        ["ModelName"] = "ConeHeadZombie",
        ["ModelTypeTag"] = "Zombie",
        ["Class"] = "CommonZombie",
    },

    ["BucketHeadZombie"] = {
        ["BiteDamage"] = 15,
        ["HP"] = 50,
        ["MaxHP"] = 50,
        ["BiteCooldown"] = 5,
        ["ModelName"] = "BucketHeadZombie",
        ["ModelTypeTag"] = "Zombie",
        ["Class"] = "CommonZombie",
    },


}
return ZombiesData 